"""ArcUI skill evaluation and golden case routes.

Drives the real Starlette app with a signed skill bundle discovered through
ArcAgent's capability inventory seam. Anchored version behavior is exercised
in test_capability_import_revision_routes.py.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
from arcagent.capabilities.capability_signing import sign
from arcgateway.team_roster import RosterEntry
from arctrust import InProcessSigner
from arctrust.identity import AgentIdentity
from starlette.testclient import TestClient

from arcui.auth import AuthConfig
from arcui.server import create_app

VIEWER_TOKEN = "viewer-tok-skillver"
OPERATOR_TOKEN = "operator-tok-skillver"

_SKILL_NAME = "planner"
_SKILL_MD = (
    "---\n"
    "name: planner\n"
    "version: 1.0.0\n"
    "description: does planning\n"
    "triggers: [planner]\n"
    "tools: [reload]\n"
    "---\n"
    "\n## Resources\n\n## Contract\n\n## Knowledge\n\n## Steps\n\n"
    "## Anti Patterns\n\n## Examples\n\n## Validation\n"
)
_HUMAN_EVAL = (
    '"""Human-authored golden cases."""\n'
    "\n"
    "def test_alpha():\n"
    "    assert 1 + 1 == 2\n"
    "\n"
    "def test_beta():\n"
    "    assert 'a'.upper() == 'A'\n"
)
_MACHINE_EVAL = (
    '"""@generated by the arc suite generator."""\n'
    "\n"
    "def test_gamma():\n"
    "    assert sorted([2, 1]) == [1, 2]\n"
)


def _viewer() -> dict[str, str]:
    return {"Authorization": f"Bearer {VIEWER_TOKEN}"}


def _operator() -> dict[str, str]:
    return {"Authorization": f"Bearer {OPERATOR_TOKEN}"}


def _write_skill_bundle(agent_dir: Path) -> None:
    """A skill bundle with evals under the agent capabilities root."""
    skill_dir = agent_dir / "capabilities" / "skills" / _SKILL_NAME
    evals = skill_dir / "evals"
    evals.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text(_SKILL_MD, encoding="utf-8")
    (evals / "test_human.py").write_text(_HUMAN_EVAL, encoding="utf-8")
    (evals / "test_machine.py").write_text(_MACHINE_EVAL, encoding="utf-8")
    # Harness manifest: the @generated marker only counts with a matching hash.
    digest = hashlib.sha256(_MACHINE_EVAL.encode("utf-8")).hexdigest()
    (evals / ".manifest.json").write_text(
        json.dumps({"files": {"test_machine.py": {"sha256": digest}}}), encoding="utf-8"
    )
    # A second skill with no evals dir — the empty-suite (200 []) case.
    bare = agent_dir / "capabilities" / "skills" / "bare"
    bare.mkdir(parents=True)
    (bare / "SKILL.md").write_text(_SKILL_MD.replace("planner", "bare"), encoding="utf-8")


def _roster(agent_dir: Path, did: str) -> list[RosterEntry]:
    return [
        RosterEntry(
            agent_id="tester",
            name="tester",
            did=did,
            org="arc",
            type="agent",
            workspace_path=str(agent_dir),
            model="claude-3-5-sonnet",
            provider="anthropic",
            online=True,
            display_name="Tester",
            color="#1abc9c",
            role_label="Test",
            hidden=False,
        )
    ]


@pytest.fixture
def app_with_skill(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[Any]:
    """Real app + real candidate store + real skill bundle for agent 'tester'."""
    monkeypatch.setenv("ARC_CONFIG_DIR", str(tmp_path / "empty-arc"))
    team_root = tmp_path / "team"
    agent_dir = team_root / "tester_agent"
    workspace = agent_dir / "workspace"
    workspace.mkdir(parents=True)

    identity = AgentIdentity.generate(org="arc", agent_type="exec")
    key_dir = tmp_path / "keys"
    identity.save_keys(key_dir)
    (agent_dir / "arcagent.toml").write_text(
        '[agent]\nname = "tester"\norg = "arc"\ntype = "exec"\n'
        f'workspace = "{workspace}"\n'
        '[llm]\nmodel = "test/model"\n'
        '[security]\ntier = "personal"\n'
        f'[identity]\ndid = "{identity.did}"\nkey_dir = "{key_dir}"\nvault_path = ""\n',
        encoding="utf-8",
    )
    _write_skill_bundle(agent_dir)
    signer = InProcessSigner(bytes(range(32)))
    for name in (_SKILL_NAME, "bare"):
        sign(
            agent_dir / "capabilities" / "skills" / name / "SKILL.md",
            signer_did="did:arc:operator:test",
            signer=signer,
            config_path=agent_dir / "arcagent.toml",
        )

    auth = AuthConfig({"viewer_token": VIEWER_TOKEN, "operator_token": OPERATOR_TOKEN})
    app = create_app(
        team_root=team_root,
        auth_config=auth,
        data_dir=tmp_path / "data",
        workspace_dir=workspace,
    )
    app.state.roster_provider = lambda: _roster(agent_dir, identity.did)
    app.state.workspace = workspace
    yield app


# ---------------------------------------------------------------------------
# GET /api/agents/{id}/skills/{skill_name}/evals — case list + provenance
# ---------------------------------------------------------------------------


class TestSkillEvals:
    def test_viewer_lists_cases_with_provenance(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(f"/api/agents/tester/skills/{_SKILL_NAME}/evals", headers=_viewer())
        assert resp.status_code == 200
        items = {it["nodeid"]: it["provenance"] for it in resp.json()["items"]}
        assert items["evals/test_human.py::test_alpha"] == "human"
        assert items["evals/test_human.py::test_beta"] == "human"
        assert items["evals/test_machine.py::test_gamma"] == "machine"

    def test_unknown_agent_is_404(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(f"/api/agents/ghost/skills/{_SKILL_NAME}/evals", headers=_viewer())
        assert resp.status_code == 404

    def test_unknown_skill_is_404(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get("/api/agents/tester/skills/no-such/evals", headers=_viewer())
        assert resp.status_code == 404

    def test_skill_without_suite_is_200_empty(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get("/api/agents/tester/skills/bare/evals", headers=_viewer())
        assert resp.status_code == 200
        assert resp.json()["items"] == []

    def test_no_auth_is_401(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(f"/api/agents/tester/skills/{_SKILL_NAME}/evals")
        assert resp.status_code == 401


# ---------------------------------------------------------------------------
# POST .../promote — operator "promote to golden" (H-041)
# ---------------------------------------------------------------------------


class TestSkillPromoteGolden:
    def _url(self) -> str:
        return f"/api/agents/tester/skills/{_SKILL_NAME}/promote"

    def test_viewer_is_403(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.post(
                self._url(),
                json={"case_id": "c", "gate_type": "exact_match", "ideal_output": "v"},
                headers=_viewer(),
            )
        assert resp.status_code == 403

    def test_without_anchor_golden_mutation_is_refused(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.post(
                self._url(),
                json={"case_id": "inv", "gate_type": "exact_match", "ideal_output": "Acme $42"},
                headers=_operator(),
            )
            assert resp.status_code == 503, resp.text
            listing = client.get(
                f"/api/agents/tester/skills/{_SKILL_NAME}/evals", headers=_viewer()
            )
        provenances = {it["provenance"] for it in listing.json()["items"]}
        assert "curated" not in provenances

    def test_unpinned_judge_rubric_is_400(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.post(
                self._url(),
                json={"case_id": "q", "gate_type": "judge_rubric", "rubric": "be nice"},
                headers=_operator(),
            )
        assert resp.status_code == 400
