"""T-734 — arcui skill evals view + version timeline/diff/rollback (COMP-010, REQ-120).

Drives the real Starlette app (``arcui.server.create_app``) against a real
candidate store built through arcskill's own write path
(``CandidateStore.save`` — never hand-written manifest JSON) and a real skill
bundle discovered through arcagent's capability inventory seam, mirroring
``test_knowledge_routes.py``'s fixture pattern.

Covers: the read-only per-skill eval-case list (nodeids + machine/human
provenance), the version timeline from the arcstore mirror (active badged,
tombstones for pruned bodies), candidate body fetch, the memoized server-side
unified diff, and the confirm-gated, audited, non-destructive rollback —
including the retired-skill rejection (revive is a distinct operation).
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
from arcgateway.team_roster import RosterEntry
from arcskill.improver.candidate_store import (  # type: ignore[import-untyped]  # reason: arcskill ships no py.typed marker
    CandidateStore,
)
from arcskill.improver.models import (  # type: ignore[import-untyped]  # reason: arcskill ships no py.typed marker
    Candidate,
)
from arctrust.identity import AgentIdentity
from starlette.testclient import TestClient

from arcui.auth import AuthConfig
from arcui.server import create_app

VIEWER_TOKEN = "viewer-tok-skillver"
OPERATOR_TOKEN = "operator-tok-skillver"

_SKILL_NAME = "planner"
_SKILL_MD = (
    "---\n"
    "name: planner\n"
    "version: 1.0.0\n"
    "description: does planning\n"
    "triggers: [planner]\n"
    "tools: [reload]\n"
    "---\n"
    "\n## Resources\n\n## Contract\n\n## Knowledge\n\n## Steps\n\n"
    "## Anti Patterns\n\n## Examples\n\n## Validation\n"
)
_HUMAN_EVAL = (
    '"""Human-authored golden cases."""\n'
    "\n"
    "def test_alpha():\n"
    "    assert 1 + 1 == 2\n"
    "\n"
    "def test_beta():\n"
    "    assert 'a'.upper() == 'A'\n"
)
_MACHINE_EVAL = (
    '"""@generated by the arc suite generator."""\n'
    "\n"
    "def test_gamma():\n"
    "    assert sorted([2, 1]) == [1, 2]\n"
)


def _viewer() -> dict[str, str]:
    return {"Authorization": f"Bearer {VIEWER_TOKEN}"}


def _operator() -> dict[str, str]:
    return {"Authorization": f"Bearer {OPERATOR_TOKEN}"}


def _write_skill_bundle(agent_dir: Path) -> None:
    """A skill bundle with evals under the agent capabilities root."""
    skill_dir = agent_dir / "capabilities" / "skills" / _SKILL_NAME
    evals = skill_dir / "evals"
    evals.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text(_SKILL_MD, encoding="utf-8")
    (evals / "test_human.py").write_text(_HUMAN_EVAL, encoding="utf-8")
    (evals / "test_machine.py").write_text(_MACHINE_EVAL, encoding="utf-8")
    # Harness manifest: the @generated marker only counts with a matching hash.
    digest = hashlib.sha256(_MACHINE_EVAL.encode("utf-8")).hexdigest()
    (evals / ".manifest.json").write_text(
        json.dumps({"files": {"test_machine.py": {"sha256": digest}}}), encoding="utf-8"
    )
    # A second skill with no evals dir — the empty-suite (200 []) case.
    bare = agent_dir / "capabilities" / "skills" / "bare"
    bare.mkdir(parents=True)
    (bare / "SKILL.md").write_text(_SKILL_MD.replace("planner", "bare"), encoding="utf-8")


def _seed_candidates(workspace: Path) -> None:
    """Three generations through arcskill's own write path; one body pruned."""
    store = CandidateStore(workspace)
    store.save_seed(_SKILL_NAME, "seed body\n")
    store.save(
        _SKILL_NAME,
        Candidate(id="aaa111", text="line one\nline two\n", generation=1),
    )
    store.save(
        _SKILL_NAME,
        Candidate(
            id="bbb222",
            text="line one\nline 2!\n",
            generation=2,
            parent_id="aaa111",
            aggregate_scores={"quality": 0.9},
        ),
        active=True,
    )
    store.save(
        _SKILL_NAME,
        Candidate(id="ccc333", text="pruned body\n", generation=3, parent_id="bbb222"),
    )
    # Prune ccc333's body before ingest — the mirror must record a tombstone.
    (workspace / "skill_traces" / _SKILL_NAME / "candidates" / "ccc333.md").unlink()


def _roster(agent_dir: Path, did: str) -> list[RosterEntry]:
    return [
        RosterEntry(
            agent_id="tester",
            name="tester",
            did=did,
            org="arc",
            type="agent",
            workspace_path=str(agent_dir),
            model="claude-3-5-sonnet",
            provider="anthropic",
            online=True,
            display_name="Tester",
            color="#1abc9c",
            role_label="Test",
            hidden=False,
        )
    ]


@pytest.fixture
def app_with_skill(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[Any]:
    """Real app + real candidate store + real skill bundle for agent 'tester'."""
    monkeypatch.setenv("ARC_CONFIG_DIR", str(tmp_path / "empty-arc"))
    team_root = tmp_path / "team"
    agent_dir = team_root / "tester_agent"
    workspace = agent_dir / "workspace"
    workspace.mkdir(parents=True)

    identity = AgentIdentity.generate(org="arc", agent_type="exec")
    key_dir = tmp_path / "keys"
    identity.save_keys(key_dir)
    (agent_dir / "arcagent.toml").write_text(
        '[agent]\nname = "tester"\norg = "arc"\ntype = "exec"\n'
        f'workspace = "{workspace}"\n'
        '[llm]\nmodel = "test/model"\n'
        '[security]\ntier = "personal"\n'
        f'[identity]\ndid = "{identity.did}"\nkey_dir = "{key_dir}"\nvault_path = ""\n',
        encoding="utf-8",
    )
    _write_skill_bundle(agent_dir)
    _seed_candidates(workspace)

    auth = AuthConfig({"viewer_token": VIEWER_TOKEN, "operator_token": OPERATOR_TOKEN})
    app = create_app(
        team_root=team_root,
        auth_config=auth,
        data_dir=tmp_path / "data",
        workspace_dir=workspace,
    )
    app.state.roster_provider = lambda: _roster(agent_dir, identity.did)
    app.state.workspace = workspace
    yield app


# ---------------------------------------------------------------------------
# GET /api/agents/{id}/skills/{skill_name}/evals — case list + provenance
# ---------------------------------------------------------------------------


class TestSkillEvals:
    def test_viewer_lists_cases_with_provenance(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(f"/api/agents/tester/skills/{_SKILL_NAME}/evals", headers=_viewer())
        assert resp.status_code == 200
        items = {it["nodeid"]: it["provenance"] for it in resp.json()["items"]}
        assert items["evals/test_human.py::test_alpha"] == "human"
        assert items["evals/test_human.py::test_beta"] == "human"
        assert items["evals/test_machine.py::test_gamma"] == "machine"

    def test_unknown_agent_is_404(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(f"/api/agents/ghost/skills/{_SKILL_NAME}/evals", headers=_viewer())
        assert resp.status_code == 404

    def test_unknown_skill_is_404(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get("/api/agents/tester/skills/no-such/evals", headers=_viewer())
        assert resp.status_code == 404

    def test_skill_without_suite_is_200_empty(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get("/api/agents/tester/skills/bare/evals", headers=_viewer())
        assert resp.status_code == 200
        assert resp.json()["items"] == []

    def test_no_auth_is_401(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(f"/api/agents/tester/skills/{_SKILL_NAME}/evals")
        assert resp.status_code == 401


# ---------------------------------------------------------------------------
# GET .../versions — metadata-only timeline from the arcstore mirror
# ---------------------------------------------------------------------------


class TestSkillVersions:
    def test_timeline_ordered_with_active_badge_and_tombstone(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(
                f"/api/agents/tester/skills/{_SKILL_NAME}/versions", headers=_viewer()
            )
        assert resp.status_code == 200
        items = resp.json()["items"]
        assert [it["candidate_id"] for it in items] == ["aaa111", "bbb222", "ccc333"]
        by_id = {it["candidate_id"]: it for it in items}
        assert by_id["bbb222"]["active"] is True
        assert by_id["aaa111"]["active"] is False
        assert by_id["bbb222"]["scores"] == {"quality": 0.9}
        assert by_id["bbb222"]["parent_id"] == "aaa111"
        # Pruned body → tombstone row, never an error.
        assert by_id["ccc333"]["tombstone"] is True
        assert by_id["ccc333"]["body_hash"] is None
        assert by_id["aaa111"]["tombstone"] is False
        # Metadata only — bodies never ride the list payload.
        assert all("body" not in it for it in items)

    def test_skill_with_no_versions_is_200_empty(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get("/api/agents/tester/skills/bare/versions", headers=_viewer())
        assert resp.status_code == 200
        assert resp.json()["items"] == []

    def test_unknown_agent_is_404(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(
                f"/api/agents/ghost/skills/{_SKILL_NAME}/versions", headers=_viewer()
            )
        assert resp.status_code == 404

    def test_unreadable_store_is_503_with_verbatim_error(self, app_with_skill: Any) -> None:
        class _BrokenObserve:
            async def skill_versions(self, skill_name: str, *, limit: int = 100) -> Any:
                raise RuntimeError("mirror exploded")

        with TestClient(app_with_skill) as client:
            app_with_skill.state.observe = _BrokenObserve()
            resp = client.get(
                f"/api/agents/tester/skills/{_SKILL_NAME}/versions", headers=_viewer()
            )
        assert resp.status_code == 503
        assert "mirror exploded" in resp.json()["error"]


# ---------------------------------------------------------------------------
# GET .../versions/{candidate_id}/body — full text, 404 tombstone
# ---------------------------------------------------------------------------


class TestSkillVersionBody:
    def test_body_fetch(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(
                f"/api/agents/tester/skills/{_SKILL_NAME}/versions/aaa111/body",
                headers=_viewer(),
            )
        assert resp.status_code == 200
        assert resp.json() == {"candidate_id": "aaa111", "body": "line one\nline two\n"}

    def test_pruned_body_is_404(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(
                f"/api/agents/tester/skills/{_SKILL_NAME}/versions/ccc333/body",
                headers=_viewer(),
            )
        assert resp.status_code == 404

    def test_unknown_candidate_is_404(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(
                f"/api/agents/tester/skills/{_SKILL_NAME}/versions/fff999/body",
                headers=_viewer(),
            )
        assert resp.status_code == 404


# ---------------------------------------------------------------------------
# GET .../versions/diff?a=&b= — server-side unified diff, memoized
# ---------------------------------------------------------------------------


class TestSkillVersionDiff:
    def test_unified_diff_between_candidates(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(
                f"/api/agents/tester/skills/{_SKILL_NAME}/versions/diff?a=aaa111&b=bbb222",
                headers=_viewer(),
            )
        assert resp.status_code == 200
        data = resp.json()
        assert data["a"] == "aaa111" and data["b"] == "bbb222"
        assert "-line two" in data["diff"]
        assert "+line 2!" in data["diff"]

    def test_missing_query_param_is_400(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(
                f"/api/agents/tester/skills/{_SKILL_NAME}/versions/diff?a=aaa111",
                headers=_viewer(),
            )
        assert resp.status_code == 400

    def test_diff_against_tombstone_is_404(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(
                f"/api/agents/tester/skills/{_SKILL_NAME}/versions/diff?a=aaa111&b=ccc333",
                headers=_viewer(),
            )
        assert resp.status_code == 404

    def test_diff_unknown_candidate_is_404(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.get(
                f"/api/agents/tester/skills/{_SKILL_NAME}/versions/diff?a=aaa111&b=fff999",
                headers=_viewer(),
            )
        assert resp.status_code == 404

    def test_diff_is_memoized_per_hash_pair(self, app_with_skill: Any) -> None:
        from arcui.routes.agent_detail.skill_versions import _unified_diff

        _unified_diff.cache_clear()
        with TestClient(app_with_skill) as client:
            for _ in range(2):
                resp = client.get(
                    f"/api/agents/tester/skills/{_SKILL_NAME}/versions/diff?a=aaa111&b=bbb222",
                    headers=_viewer(),
                )
                assert resp.status_code == 200
        info = _unified_diff.cache_info()
        assert info.misses == 1
        assert info.hits == 1


# ---------------------------------------------------------------------------
# POST .../rollback — confirm-gated, audited, non-destructive
# ---------------------------------------------------------------------------


class TestSkillRollback:
    def _url(self) -> str:
        return f"/api/agents/tester/skills/{_SKILL_NAME}/rollback"

    def test_viewer_is_403(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.post(
                self._url(), json={"candidate_id": "aaa111", "confirm": True}, headers=_viewer()
            )
        assert resp.status_code == 403

    def test_missing_confirm_is_400_and_no_flip(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.post(self._url(), json={"candidate_id": "aaa111"}, headers=_operator())
        assert resp.status_code == 400
        assert "confirm" in resp.json()["error"]
        store = CandidateStore(app_with_skill.state.workspace)
        assert store.load_manifest(_SKILL_NAME)["active_candidate_id"] == "bbb222"

    def test_missing_candidate_id_is_400(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.post(self._url(), json={"confirm": True}, headers=_operator())
        assert resp.status_code == 400

    def test_invalid_json_body_is_400(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.post(
                self._url(),
                content=b"not json",
                headers={**_operator(), "Content-Type": "application/json"},
            )
        assert resp.status_code == 400

    def test_unknown_candidate_is_404(self, app_with_skill: Any) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.post(
                self._url(), json={"candidate_id": "fff999", "confirm": True}, headers=_operator()
            )
        assert resp.status_code == 404

    def test_rollback_flips_manifest_and_warns_scores_historical(
        self, app_with_skill: Any
    ) -> None:
        with TestClient(app_with_skill) as client:
            resp = client.post(
                self._url(), json={"candidate_id": "aaa111", "confirm": True}, headers=_operator()
            )
        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "applied"
        assert data["from_candidate_id"] == "bbb222"
        assert data["to_candidate_id"] == "aaa111"
        assert "historical" in data["warning"]
        # Non-destructive flip: the manifest points back, nothing is deleted.
        store = CandidateStore(app_with_skill.state.workspace)
        manifest = store.load_manifest(_SKILL_NAME)
        assert manifest["active_candidate_id"] == "aaa111"
        assert set(manifest["candidates"]) == {"aaa111", "bbb222", "ccc333"}

    def test_rollback_emits_one_ui_mutation_audit_event(
        self, app_with_skill: Any, caplog: pytest.LogCaptureFixture
    ) -> None:
        with TestClient(app_with_skill) as client:
            with caplog.at_level("INFO", logger="arcui.audit"):
                resp = client.post(
                    self._url(),
                    json={"candidate_id": "aaa111", "confirm": True},
                    headers=_operator(),
                )
        assert resp.status_code == 200
        mutations = [
            json.loads(r.message)
            for r in caplog.records
            if r.name == "arcui.audit" and '"ui.mutation"' in r.message
        ]
        assert len(mutations) == 1
        details = mutations[0]["details"]
        assert details["actor_role"] == "operator"
        assert details["operation"] == "skill.rollback"
        assert details["outcome"] == "applied"
        assert _SKILL_NAME in details["target"]
        assert "from=bbb222" in details["detail"]
        assert "to=aaa111" in details["detail"]

    def test_retired_skill_is_409_and_no_flip(self, app_with_skill: Any) -> None:
        store = CandidateStore(app_with_skill.state.workspace)
        store.set_lifecycle_state(_SKILL_NAME, "retired", reason="unused")
        with TestClient(app_with_skill) as client:
            resp = client.post(
                self._url(), json={"candidate_id": "aaa111", "confirm": True}, headers=_operator()
            )
        assert resp.status_code == 409
        assert "retired" in resp.json()["error"]
        assert store.load_manifest(_SKILL_NAME)["active_candidate_id"] == "bbb222"


# ---------------------------------------------------------------------------
# Ingest wiring — workspace_dir reaches StoreIngest through Observe
# ---------------------------------------------------------------------------


class TestObserveWorkspaceWiring:
    async def test_observe_ingests_candidate_store_via_workspace_dir(self, tmp_path: Path) -> None:
        from arcui.observe import Observe

        workspace = tmp_path / "workspace"
        workspace.mkdir()
        _seed_candidates(workspace)

        obs = Observe(data_dir=tmp_path / "data", workspace_dir=workspace)
        await obs.start()
        try:
            rows = await obs.skill_versions(_SKILL_NAME)
        finally:
            await obs.stop()
        assert [r["candidate_id"] for r in rows] == ["aaa111", "bbb222", "ccc333"]
        body = None
        obs2 = Observe(data_dir=tmp_path / "data", workspace_dir=workspace)
        await obs2.start()
        try:
            body = await obs2.skill_candidate_body(_SKILL_NAME, "aaa111")
        finally:
            await obs2.stop()
        assert body == "line one\nline two\n"
