"""Top-level ``arc init`` setup wizard — tier-based configuration.

Generates config files with module presets for open, enterprise, or
federal deployment tiers.  Optionally scaffolds a first agent for
immediate use.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import click

from arccli.formatting import click_echo, print_kv

# ---------------------------------------------------------------------------
# Tier presets — which modules are enabled at each tier
# ---------------------------------------------------------------------------

_TIER_PRESETS: dict[str, dict[str, dict[str, Any]]] = {
    "open": {
        "routing": {"enabled": False},
        "telemetry": {"enabled": False},
        "audit": {"enabled": False},
        "retry": {"enabled": False},
        "fallback": {"enabled": False},
        "rate_limit": {"enabled": False},
        "otel": {"enabled": False},
        "security": {"enabled": False},
    },
    "enterprise": {
        "routing": {"enabled": False},
        "telemetry": {"enabled": True, "log_level": "INFO"},
        "audit": {"enabled": True},
        "retry": {"enabled": True, "max_retries": 3, "backoff_base_seconds": 1.0},
        "fallback": {"enabled": True, "chain": ["anthropic", "openai"]},
        "rate_limit": {"enabled": True, "requests_per_minute": 60, "burst_capacity": 60},
        "otel": {"enabled": False},
        "security": {"enabled": False},
    },
    "federal": {
        "routing": {
            "enabled": True,
            "enforcement": "block",
            "default_classification": "unclassified",
        },
        "telemetry": {"enabled": True, "log_level": "INFO"},
        "audit": {"enabled": True},
        "retry": {"enabled": True, "max_retries": 3, "backoff_base_seconds": 1.0},
        "fallback": {"enabled": True, "chain": ["anthropic", "openai"]},
        "rate_limit": {"enabled": True, "requests_per_minute": 60, "burst_capacity": 60},
        "otel": {
            "enabled": True,
            "exporter": "otlp",
            "endpoint": "http://localhost:4317",
            "protocol": "grpc",
            "service_name": "arcllm",
            "sample_rate": 1.0,
        },
        "security": {
            "enabled": True,
            "pii_enabled": True,
            "pii_detector": "regex",
            "signing_enabled": True,
            "signing_algorithm": "hmac-sha256",
            "signing_key_env": "ARCLLM_SIGNING_KEY",
        },
    },
}

_VALID_TIERS = list(_TIER_PRESETS.keys())


# ---------------------------------------------------------------------------
# TOML generation
# ---------------------------------------------------------------------------


def _generate_config_toml(tier: str, provider: str = "anthropic") -> str:
    """Generate config.toml content for a given tier."""
    preset = _TIER_PRESETS[tier]
    lines = [
        f"# Arc global config — tier: {tier}",
        f"# Generated by `arc init --tier {tier}`",
        "",
        "[defaults]",
        f'provider = "{provider}"',
        "temperature = 0.7",
        "max_tokens = 4096",
        "",
        "[vault]",
        'backend = ""',
        "cache_ttl_seconds = 300",
        'url = ""',
        'region = ""',
        "",
    ]

    for module_name, settings in preset.items():
        lines.append(f"[modules.{module_name}]")
        for key, val in settings.items():
            if isinstance(val, bool):
                lines.append(f"{key} = {'true' if val else 'false'}")
            elif isinstance(val, str):
                lines.append(f'{key} = "{val}"')
            elif isinstance(val, (int, float)):
                lines.append(f"{key} = {val}")
            elif isinstance(val, list):
                items = ", ".join(f'"{v}"' for v in val)
                lines.append(f"{key} = [{items}]")
        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Provider key validation
# ---------------------------------------------------------------------------

_PROVIDER_ENV_VARS: dict[str, str] = {
    "anthropic": "ANTHROPIC_API_KEY",
    "openai": "OPENAI_API_KEY",
    "google": "GOOGLE_API_KEY",
    "groq": "GROQ_API_KEY",
    "mistral": "MISTRAL_API_KEY",
    "deepseek": "DEEPSEEK_API_KEY",
    "ollama": "",
    "lmstudio": "",
}

_VALID_PROVIDERS = list(_PROVIDER_ENV_VARS.keys())


def _check_provider_key(provider: str) -> bool:
    """Check if the provider's API key env var is set."""
    env_var = _PROVIDER_ENV_VARS.get(provider, "")
    if not env_var:
        return True  # local providers don't need keys
    return bool(os.environ.get(env_var, ""))


# ---------------------------------------------------------------------------
# CLI command
# ---------------------------------------------------------------------------


@click.command("init")
@click.option(
    "--tier",
    type=click.Choice(_VALID_TIERS),
    default=None,
    help="Deployment tier (open/enterprise/federal).",
)
@click.option(
    "--dir",
    "config_dir",
    type=click.Path(),
    default=None,
    help="Config directory (default: ~/.arc).",
)
@click.option(
    "--provider",
    default=None,
    help="Default LLM provider.",
)
@click.option(
    "--quick",
    is_flag=True,
    help="Quick start — open tier + first agent in one step.",
)
def init(
    tier: str | None,
    config_dir: str | None,
    provider: str | None,
    quick: bool,
) -> None:
    """Initialize Arc — configure deployment tier and write config files."""
    click_echo("")
    click_echo("  Arc — Security-First Agent Framework")
    click_echo("  ====================================")
    click_echo("")

    if quick:
        tier = "open"
    elif tier is None:
        click_echo("  How do you want to deploy?")
        click_echo("")
        click_echo("  1) quick start  — Minimal config, create an agent immediately")
        click_echo("  2) open         — No security modules, basic defaults")
        click_echo("  3) enterprise   — Telemetry, audit, rate limiting, retry + fallback")
        click_echo("  4) federal      — Full security: routing, PII, signing, OTel, audit")
        click_echo("")
        choice = click.prompt(
            "  Select",
            type=click.Choice(["1", "2", "3", "4"]),
            default="1",
        )
        tier_map = {"1": "open", "2": "open", "3": "enterprise", "4": "federal"}
        tier = tier_map[choice]
        quick = choice == "1"

    # Interactive provider selection if not provided
    if provider is None:
        click_echo("")
        click_echo("  LLM Providers:")
        click_echo("    Cloud:  anthropic, openai, google, groq, mistral, deepseek")
        click_echo("    Local:  ollama, lmstudio (no API key needed)")
        click_echo("")
        provider = click.prompt(
            "  Default provider",
            type=click.Choice(_VALID_PROVIDERS),
            default="anthropic",
        )

    arc_dir = Path(config_dir) if config_dir else Path.home() / ".arc"
    arc_dir.mkdir(parents=True, exist_ok=True)

    # Write config.toml
    config_path = arc_dir / "config.toml"
    config_content = _generate_config_toml(tier, provider)

    if config_path.exists() and not quick:
        if not click.confirm(f"  {config_path} already exists. Overwrite?", default=False):
            click_echo("  Aborted.")
            return

    config_path.write_text(config_content, encoding="utf-8")

    # Create .env file if it doesn't exist
    env_path = arc_dir / ".env"
    if not env_path.exists():
        env_path.touch(mode=0o600)

    # Create team directory if enterprise or federal
    if tier in ("enterprise", "federal"):
        team_dir = arc_dir / "team"
        for sub in ("entities", "channels", "cursors"):
            (team_dir / sub).mkdir(parents=True, exist_ok=True)

    # Validate provider key
    key_ok = _check_provider_key(provider)
    env_var = _PROVIDER_ENV_VARS.get(provider, "")

    click_echo("")
    click_echo("  Configuration Summary:")
    print_kv(
        [
            ("Tier", tier),
            ("Provider", provider),
            ("Config", str(config_path)),
            ("API key", "OK" if key_ok else f"MISSING ({env_var})"),
        ]
    )

    if not key_ok:
        click_echo("")
        click_echo("  Set your API key:")
        click_echo(f"    export {env_var}=<your-key>")
        click_echo("")
        click_echo(f"  Or add it to {env_path}:")
        click_echo(f"    echo '{env_var}=sk-...' >> {env_path}")

    # Quick start: create first agent
    if quick:
        click_echo("")
        agent_name = click.prompt("  Name your first agent", default="assistant")
        click_echo("")
        _create_quick_agent(arc_dir, agent_name)

    click_echo("")


def _create_quick_agent(arc_dir: Path, name: str) -> None:
    """Create a minimal agent directory for quick start."""
    # Import here to avoid circular dependency

    # Use ~/.arc/agents/<name> as the default location
    agents_dir = arc_dir / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    agent_dir = agents_dir / name

    if agent_dir.exists():
        click_echo(f"  Agent '{name}' already exists at {agent_dir}")
        click_echo(f"  Start chatting: arc agent chat {agent_dir}")
        return

    # Delegate to the existing create logic via CLI invocation
    from click.testing import CliRunner

    from arccli.agent import agent

    runner = CliRunner()
    result = runner.invoke(agent, ["create", str(agent_dir)])

    if result.exit_code == 0:
        click_echo(f"  Agent created at {agent_dir}")
        click_echo("")
        click_echo("  Get started:")
        click_echo(f"    arc agent chat {agent_dir}")
    else:
        # Fallback: create minimal structure manually
        agent_dir.mkdir(parents=True, exist_ok=True)
        (agent_dir / "workspace").mkdir(exist_ok=True)

        identity = (
            "# Agent Identity\n\n"
            "You are a helpful assistant with access to tools "
            "and a structured workspace.\n"
        )
        (agent_dir / "identity.md").write_text(identity)

        config = (
            '# Agent config\ntier = "open"\n\n[modules]\n[modules.bio_memory]\nenabled = true\n'
        )
        (agent_dir / "arcagent.toml").write_text(config)

        (agent_dir / "context.md").write_text("# Context\n\nNo context yet.\n")
        (agent_dir / "policy.md").write_text(
            "# Policy\n\n## Approved Behaviors\n\n## Denied Behaviors\n"
        )

        click_echo(f"  Agent created at {agent_dir}")
        click_echo("")
        click_echo("  Get started:")
        click_echo(f"    arc agent chat {agent_dir}")
