"""Top-level ``arc init`` setup wizard — tier-based configuration.

Generates config files with module presets for open, enterprise, or
federal deployment tiers.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import click

from arccli.formatting import click_echo, print_kv

# ---------------------------------------------------------------------------
# Tier presets — which modules are enabled at each tier
# ---------------------------------------------------------------------------

_TIER_PRESETS: dict[str, dict[str, dict[str, Any]]] = {
    "open": {
        "routing": {"enabled": False},
        "telemetry": {"enabled": False},
        "audit": {"enabled": False},
        "retry": {"enabled": False},
        "fallback": {"enabled": False},
        "rate_limit": {"enabled": False},
        "otel": {"enabled": False},
        "security": {"enabled": False},
    },
    "enterprise": {
        "routing": {"enabled": False},
        "telemetry": {"enabled": True, "log_level": "INFO"},
        "audit": {"enabled": True},
        "retry": {"enabled": True, "max_retries": 3, "backoff_base_seconds": 1.0},
        "fallback": {"enabled": True, "chain": ["anthropic", "openai"]},
        "rate_limit": {"enabled": True, "requests_per_minute": 60, "burst_capacity": 60},
        "otel": {"enabled": False},
        "security": {"enabled": False},
    },
    "federal": {
        "routing": {
            "enabled": True,
            "enforcement": "block",
            "default_classification": "unclassified",
        },
        "telemetry": {"enabled": True, "log_level": "INFO"},
        "audit": {"enabled": True},
        "retry": {"enabled": True, "max_retries": 3, "backoff_base_seconds": 1.0},
        "fallback": {"enabled": True, "chain": ["anthropic", "openai"]},
        "rate_limit": {"enabled": True, "requests_per_minute": 60, "burst_capacity": 60},
        "otel": {
            "enabled": True,
            "exporter": "otlp",
            "endpoint": "http://localhost:4317",
            "protocol": "grpc",
            "service_name": "arcllm",
            "sample_rate": 1.0,
        },
        "security": {
            "enabled": True,
            "pii_enabled": True,
            "pii_detector": "regex",
            "signing_enabled": True,
            "signing_algorithm": "hmac-sha256",
            "signing_key_env": "ARCLLM_SIGNING_KEY",
        },
    },
}

_VALID_TIERS = list(_TIER_PRESETS.keys())


# ---------------------------------------------------------------------------
# TOML generation
# ---------------------------------------------------------------------------


def _generate_config_toml(tier: str, provider: str = "anthropic") -> str:
    """Generate config.toml content for a given tier."""
    preset = _TIER_PRESETS[tier]
    lines = [
        f"# Arc global config — tier: {tier}",
        f"# Generated by `arc init --tier {tier}`",
        "",
        "[defaults]",
        f'provider = "{provider}"',
        "temperature = 0.7",
        "max_tokens = 4096",
        "",
        "[vault]",
        'backend = ""',
        "cache_ttl_seconds = 300",
        'url = ""',
        'region = ""',
        "",
    ]

    for module_name, settings in preset.items():
        lines.append(f"[modules.{module_name}]")
        for key, val in settings.items():
            if isinstance(val, bool):
                lines.append(f"{key} = {'true' if val else 'false'}")
            elif isinstance(val, str):
                lines.append(f'{key} = "{val}"')
            elif isinstance(val, (int, float)):
                lines.append(f"{key} = {val}")
            elif isinstance(val, list):
                items = ", ".join(f'"{v}"' for v in val)
                lines.append(f"{key} = [{items}]")
        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Provider key validation
# ---------------------------------------------------------------------------

_PROVIDER_ENV_VARS: dict[str, str] = {
    "anthropic": "ANTHROPIC_API_KEY",
    "openai": "OPENAI_API_KEY",
    "google": "GOOGLE_API_KEY",
    "groq": "GROQ_API_KEY",
    "mistral": "MISTRAL_API_KEY",
    "deepseek": "DEEPSEEK_API_KEY",
    "ollama": "",
    "lmstudio": "",
}


def _check_provider_key(provider: str) -> bool:
    """Check if the provider's API key env var is set."""
    env_var = _PROVIDER_ENV_VARS.get(provider, "")
    if not env_var:
        return True  # local providers don't need keys
    return bool(os.environ.get(env_var, ""))


# ---------------------------------------------------------------------------
# CLI command
# ---------------------------------------------------------------------------


@click.command("init")
@click.option(
    "--tier",
    type=click.Choice(_VALID_TIERS),
    default=None,
    help="Deployment tier (open/enterprise/federal).",
)
@click.option(
    "--dir",
    "config_dir",
    type=click.Path(),
    default=None,
    help="Config directory (default: ~/.arc).",
)
@click.option(
    "--provider",
    default=None,
    help="Default LLM provider.",
)
def init(tier: str | None, config_dir: str | None, provider: str | None) -> None:
    """Initialize Arc — configure deployment tier and write config files."""
    # Interactive tier selection if not provided
    if tier is None:
        click_echo("Arc Setup Wizard")
        click_echo("================")
        click_echo("")
        click_echo("Select a deployment tier:")
        click_echo("")
        click_echo("  open       — No security modules, no audit, basic defaults")
        click_echo("  enterprise — Telemetry, audit, rate limiting, retry + fallback")
        click_echo("  federal    — All security enabled: routing, PII, signing, OTel, audit")
        click_echo("")
        tier = click.prompt(
            "Tier",
            type=click.Choice(_VALID_TIERS),
            default="open",
        )

    # Interactive provider selection if not provided
    if provider is None:
        provider = click.prompt(
            "Default LLM provider",
            default="anthropic",
        )

    arc_dir = Path(config_dir) if config_dir else Path.home() / ".arc"
    arc_dir.mkdir(parents=True, exist_ok=True)

    # Write config.toml
    config_path = arc_dir / "config.toml"
    config_content = _generate_config_toml(tier, provider)

    if config_path.exists():
        if not click.confirm(f"{config_path} already exists. Overwrite?", default=False):
            click_echo("Aborted.")
            return

    config_path.write_text(config_content, encoding="utf-8")
    click_echo(f"Wrote config: {config_path}")

    # Create team directory if enterprise or federal
    if tier in ("enterprise", "federal"):
        team_dir = arc_dir / "team"
        for sub in ("entities", "channels", "cursors"):
            (team_dir / sub).mkdir(parents=True, exist_ok=True)
        click_echo(f"Created team directory: {team_dir}")

    # Validate provider key
    key_ok = _check_provider_key(provider)
    env_var = _PROVIDER_ENV_VARS.get(provider, "")

    click_echo("")
    click_echo("Configuration Summary:")
    print_kv(
        [
            ("Tier", tier),
            ("Provider", provider),
            ("Config", str(config_path)),
            ("API key", "OK" if key_ok else f"MISSING ({env_var})"),
        ]
    )

    if not key_ok:
        click_echo("")
        click_echo(f"Set your API key: export {env_var}=<your-key>")
