"""SPEC-054 COMP-002 — eval-case provenance + tier-aware gate (REQ-109/110/111).

Machine-authored golden cases are detected from an ``@generated`` token in the file's
module docstring during ``load_suite``'s existing AST pass, cross-checked against the
harness-written manifest at ``evals/.manifest.json`` (the model can never self-assert
provenance). Enterprise/federal count only human-authored cases toward
``min_golden_cases``; placeholder-only suites classify as empty so ``no_suite_policy``
governs (closes the fail-closed bypass).
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest
from arcskill.improver.evalgate import EvalGate, load_suite
from arcskill.improver.models import BundleView, EvalCase, EvalOutcome


class _FakeRunner:
    """Deterministic EvalRunner: maps (skill text) -> set of passing case ids."""

    def __init__(self, passing_by_text: dict[str, set[str]]) -> None:
        self._passing = passing_by_text

    async def run(self, view: BundleView, cases: list[EvalCase]) -> list[EvalOutcome]:
        passing = self._passing.get(view.text, set())
        return [EvalOutcome(case_id=c.id, passed=c.id in passing) for c in cases]


def _view(text: str) -> BundleView:
    return BundleView(skill_name="s", text=text)


_GENERATED_DOCSTRING = '"""@generated by the arc skill improver — do not edit by hand."""\n\n'

# Mirrors the create_skill scaffold in arcagent.builtins.capabilities.create_skill —
# the exact file shape the placeholder-only classification must treat as no-suite.
_PLACEHOLDER_SCAFFOLD = '''\
"""Golden-task suite for this skill (SPEC-044 REQ-070)."""


def test_placeholder() -> None:
    """Runnable-but-empty scaffold. Replace with a real golden-task assertion."""
    assert True
'''


def _write_eval_file(skill_dir: Path, name: str, body: str, *, generated: bool = False) -> Path:
    evals = skill_dir / "evals"
    evals.mkdir(exist_ok=True)
    content = (_GENERATED_DOCSTRING if generated else "") + body
    path = evals / name
    path.write_text(content, encoding="utf-8")
    return path


def _write_manifest(skill_dir: Path, files: dict[str, str]) -> None:
    """Write the harness manifest: evals-relative filename -> sha256 of file bytes."""
    manifest = {"files": {name: {"sha256": digest} for name, digest in files.items()}}
    (skill_dir / "evals" / ".manifest.json").write_text(json.dumps(manifest), encoding="utf-8")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _human_cases(n: int) -> list[EvalCase]:
    return [
        EvalCase(id=f"h{i}", node=f"evals/test_h.py::test_{i}", machine_authored=False)
        for i in range(n)
    ]


def _machine_cases(n: int) -> list[EvalCase]:
    return [
        EvalCase(id=f"m{i}", node=f"evals/test_m.py::test_{i}", machine_authored=True)
        for i in range(n)
    ]


# -- provenance detection in load_suite (REQ-109) ------------------------------


def test_load_suite_generated_file_with_manifest_entry_is_machine_authored(
    tmp_path: Path,
) -> None:
    path = _write_eval_file(
        tmp_path,
        "test_golden_generated.py",
        "def test_gen():\n    assert 'a'.upper() == 'A'\n",
        generated=True,
    )
    _write_manifest(tmp_path, {"test_golden_generated.py": _sha256(path)})

    cases = load_suite(tmp_path)

    assert len(cases) == 1
    assert cases[0].machine_authored is True


def test_load_suite_unmarked_file_is_human_authored(tmp_path: Path) -> None:
    _write_eval_file(tmp_path, "test_golden.py", "def test_real():\n    assert 1 + 2 == 3\n")

    cases = load_suite(tmp_path)

    assert len(cases) == 1
    assert cases[0].machine_authored is False


def test_load_suite_marker_without_manifest_entry_is_untrusted_machine_authored(
    tmp_path: Path,
) -> None:
    """A model-emitted @generated marker with no harness manifest entry never counts as human."""
    trusted = _write_eval_file(
        tmp_path,
        "test_trusted.py",
        "def test_ok():\n    assert 'x' * 2 == 'xx'\n",
        generated=True,
    )
    _write_eval_file(
        tmp_path,
        "test_spoofed.py",
        "def test_spoof():\n    assert len('ab') == 2\n",
        generated=True,
    )
    _write_manifest(tmp_path, {"test_trusted.py": _sha256(trusted)})

    by_node = {c.node: c for c in load_suite(tmp_path)}

    assert by_node["evals/test_spoofed.py::test_spoof"].machine_authored is True


def test_load_suite_hash_mismatch_reclassifies_as_human_authored(tmp_path: Path) -> None:
    """A human edit (content diverges from the manifest hash) strips machine status (REQ-111)."""
    _write_eval_file(
        tmp_path,
        "test_edited.py",
        "def test_edited():\n    assert 3 - 1 == 2\n",
        generated=True,
    )
    _write_manifest(tmp_path, {"test_edited.py": hashlib.sha256(b"stale content").hexdigest()})

    cases = load_suite(tmp_path)

    assert len(cases) == 1
    assert cases[0].machine_authored is False


# -- tier-aware min_golden_cases (REQ-110) -------------------------------------


@pytest.mark.asyncio
@pytest.mark.parametrize("tier", ["enterprise", "federal"])
async def test_gate_code_min_counts_only_human_cases_at_elevated_tiers(tier: str) -> None:
    """1 human + 3 machine at min=3: machine cases are supplemental, gate rejects."""
    cases = _human_cases(1) + _machine_cases(3)
    runner = _FakeRunner({"before": set(), "after": {"h0"}})
    gate = EvalGate(runner, min_golden_cases=3)

    dec = await gate.decide(
        before=_view("before"), after=_view("after"), cases=cases, tier=tier, kind="code"
    )

    assert dec.accepted is False
    assert dec.newly_passing == 0


@pytest.mark.asyncio
async def test_gate_code_min_counts_machine_cases_at_personal_tier() -> None:
    """1 human + 2 machine at min=3: personal counts all cases, gate proceeds and accepts."""
    cases = _human_cases(1) + _machine_cases(2)
    runner = _FakeRunner({"before": set(), "after": {"h0"}})
    gate = EvalGate(runner, min_golden_cases=3)

    dec = await gate.decide(
        before=_view("before"), after=_view("after"), cases=cases, tier="personal", kind="code"
    )

    assert dec.accepted is True
    assert dec.newly_passing == 1


@pytest.mark.asyncio
async def test_gate_machine_case_still_counts_in_strict_improvement_at_federal() -> None:
    """With the human minimum met, a machine case flipping fail->pass is an improvement."""
    cases = _human_cases(3) + _machine_cases(1)
    runner = _FakeRunner({"before": {"h0", "h1", "h2"}, "after": {"h0", "h1", "h2", "m0"}})
    gate = EvalGate(runner, min_golden_cases=3)

    dec = await gate.decide(
        before=_view("before"), after=_view("after"), cases=cases, tier="federal", kind="code"
    )

    assert dec.accepted is True
    assert dec.newly_passing == 1


# -- placeholder-only suites classify as empty (fail-closed bypass) ------------


def test_load_suite_placeholder_only_suite_is_empty(tmp_path: Path) -> None:
    _write_eval_file(tmp_path, "test_golden.py", _PLACEHOLDER_SCAFFOLD)

    assert load_suite(tmp_path) == []


def test_load_suite_keeps_real_case_and_drops_placeholder(tmp_path: Path) -> None:
    _write_eval_file(
        tmp_path,
        "test_mixed.py",
        "def test_placeholder():\n    assert True\n\n"
        "def test_real():\n    assert 'arc'.upper() == 'ARC'\n",
    )

    nodes = [c.node for c in load_suite(tmp_path)]

    assert nodes == ["evals/test_mixed.py::test_real"]


@pytest.mark.asyncio
async def test_gate_treats_placeholder_only_suite_as_no_suite_at_enterprise(
    tmp_path: Path,
) -> None:
    """A placeholder scaffold must not satisfy the gate: no_suite_policy governs instead."""
    _write_eval_file(tmp_path, "test_golden.py", _PLACEHOLDER_SCAFFOLD)
    cases = load_suite(tmp_path)
    # Runner that would pass every discovered case — if the placeholder leaks through as a
    # real case, the gate wrongly sees a strict improvement and accepts.
    runner = _FakeRunner({"after": {c.id for c in cases}})
    gate = EvalGate(runner)

    dec = await gate.decide(
        before=_view("before"), after=_view("after"), cases=cases, tier="enterprise", kind="prose"
    )

    assert dec.accepted is False
    assert "no golden-task suite" in dec.reason
