"""Plain CommandDef handlers for the `arc init` wizard.

Non-interactive path runs from --tier / --provider / --dir flags.
The interactive path prompts via stdlib `input()` when no flags are passed.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Tier / provider data (duplicated from init_wizard.py to avoid click import)
# ---------------------------------------------------------------------------

_TIER_PRESETS: dict[str, dict[str, dict[str, Any]]] = {
    "personal": {
        "routing": {"enabled": False},
        "telemetry": {"enabled": False},
        "audit": {"enabled": False},
        "retry": {"enabled": False},
        "fallback": {"enabled": False},
        "rate_limit": {"enabled": False},
        "otel": {"enabled": False},
        "security": {"enabled": False},
    },
    "enterprise": {
        "routing": {"enabled": False},
        "telemetry": {"enabled": True, "log_level": "INFO"},
        "audit": {"enabled": True},
        "retry": {"enabled": True, "max_retries": 3, "backoff_base_seconds": 1.0},
        "fallback": {"enabled": True, "chain": ["anthropic", "openai"]},
        "rate_limit": {"enabled": True, "requests_per_minute": 60, "burst_capacity": 60},
        "otel": {"enabled": False},
        "security": {"enabled": False},
    },
    "federal": {
        "routing": {
            "enabled": True,
            "enforcement": "block",
            "default_classification": "unclassified",
        },
        "telemetry": {"enabled": True, "log_level": "INFO"},
        "audit": {"enabled": True},
        "retry": {"enabled": True, "max_retries": 3, "backoff_base_seconds": 1.0},
        "fallback": {"enabled": True, "chain": ["anthropic", "openai"]},
        "rate_limit": {"enabled": True, "requests_per_minute": 60, "burst_capacity": 60},
        "otel": {
            "enabled": True,
            "exporter": "otlp",
            "endpoint": "http://localhost:4317",
            "protocol": "grpc",
            "service_name": "arcllm",
            "sample_rate": 1.0,
        },
        "security": {
            "enabled": True,
            "pii_enabled": True,
            "pii_detector": "regex",
            "signing_enabled": True,
            "signing_algorithm": "ed25519",
            "signing_key_env": "ARCLLM_SIGNING_KEY",
        },
    },
}

_VALID_TIERS = list(_TIER_PRESETS.keys())

_PROVIDER_ENV_VARS: dict[str, str] = {
    "anthropic": "ANTHROPIC_API_KEY",
    "openai": "OPENAI_API_KEY",
    "google": "GOOGLE_API_KEY",
    "groq": "GROQ_API_KEY",
    "mistral": "MISTRAL_API_KEY",
    "deepseek": "DEEPSEEK_API_KEY",
    "ollama": "",
    "lmstudio": "",
}

_VALID_PROVIDERS = list(_PROVIDER_ENV_VARS.keys())


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _write(msg: str = "") -> None:
    """Write a line to stdout."""
    sys.stdout.write(msg + "\n")


def _print_kv(pairs: list[tuple[str, str]]) -> None:
    """Print key-value pairs in aligned format."""
    try:
        from arccli.formatting import print_kv

        print_kv(pairs)
    except ImportError:
        width = max(len(k) for k, _ in pairs) if pairs else 0
        for k, v in pairs:
            sys.stdout.write(f"  {k:<{width}}  {v}\n")


_USER_CONFIG_HEADER = """# Arc {pkg} config — user-wide overrides
# Generated by `arc init --tier {tier}`
#
# This file deep-merges OVER the packaged defaults. Values you set here win;
# anything you omit falls through to the packaged defaults shipped with the
# {pkg} package. Per-instance configs (e.g. team/<agent>/arcagent.toml) merge
# on top of this file. Env vars override everything.
"""


def _toml_value(val: Any) -> str:
    """Render a Python value as a TOML scalar/array literal."""
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, str):
        return f'"{val}"'
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, list):
        return "[" + ", ".join(_toml_value(v) for v in val) + "]"
    raise ValueError(f"Unsupported TOML value type: {type(val).__name__}")


def _emit_module_blocks(preset: dict[str, dict[str, Any]]) -> list[str]:
    """Render [modules.<name>] blocks from a tier preset."""
    lines: list[str] = []
    for module_name, settings in preset.items():
        lines.append(f"[modules.{module_name}]")
        for key, val in settings.items():
            lines.append(f"{key} = {_toml_value(val)}")
        lines.append("")
    return lines


def _generate_arcllm_toml(tier: str, provider: str = "anthropic") -> str:
    """Generate ~/.arc/arcllm.toml content for a given tier."""
    preset = _TIER_PRESETS[tier]
    lines = [
        _USER_CONFIG_HEADER.format(pkg="arcllm", tier=tier),
        "[defaults]",
        f'provider = "{provider}"',
        "temperature = 0.7",
        "max_tokens = 4096",
        "",
        "[vault]",
        'backend = ""',
        "cache_ttl_seconds = 300",
        'url = ""',
        'region = ""',
        "",
        *_emit_module_blocks(preset),
    ]
    return "\n".join(lines) + "\n"


def _arcagent_base_config(tier: str) -> dict[str, Any]:
    """User-wide arcagent DEFAULTS as a dict (so a blueprint can deep-merge under them).

    No agent identity — name/did live in team/<agent>/arcagent.toml. ``tier`` is already
    a security-vocab value (personal/enterprise/federal); there is no normalization fork.
    """
    return {
        "security": {"tier": tier, "validators": {"auto_run_agent_code": False}},
        "telemetry": {"enabled": True, "log_level": "INFO", "export_traces": False},
        "context": {
            "max_tokens": 200000,
            "prune_threshold": 0.70,
            "compact_threshold": 0.85,
            "emergency_threshold": 0.95,
        },
        "eval": {"provider": "", "model": "", "max_tokens": 1024, "temperature": 0.2},
        "session": {"retention_count": 50, "retention_days": 30},
    }


def _generate_arcagent_toml(tier: str, blueprint_name: str | None = None) -> tuple[str, str]:
    """Render ~/.arc/arcagent.toml. Returns ``(content, effective_tier)``.

    With ``blueprint_name`` the preset is verified + deep-merged UNDER the init defaults
    (defaults win over the blueprint), the tier floored by stringency-max, and the apply
    audited. Written concretely (dict -> TOML) so the layered CLI/gateway load reads it.
    """
    from arcagent.blueprints import dumps_toml

    base = _arcagent_base_config(tier)
    effective = tier
    if blueprint_name:
        from arcagent.blueprints import apply_blueprint, resolve_blueprint

        from arccli.commands.blueprint import audit_apply

        bp = resolve_blueprint(blueprint_name, tier=tier)
        base = apply_blueprint(bp, base, deployment_tier=tier)
        effective = str(base.get("security", {}).get("tier", tier))
        audit_apply(bp, base, Path.home() / ".arc")
    header = _USER_CONFIG_HEADER.format(pkg="arcagent", tier=tier)
    return header + "\n" + dumps_toml(base), effective


def _generate_gateway_toml(tier: str) -> str:
    """Generate ~/.arc/gateway.toml content for a given tier."""
    lines = [
        _USER_CONFIG_HEADER.format(pkg="gateway", tier=tier),
        "[gateway]",
        f'tier = "{tier}"',
        'agent_did = ""',
        "",
        "[security]",
        "require_pairing = true",
        "",
        "[platforms.telegram]",
        "enabled = false",
        'bot_token_env = "TELEGRAM_BOT_TOKEN"',
        "",
        "[platforms.slack]",
        "enabled = false",
        'bot_token_env = "SLACK_BOT_TOKEN"',
        "",
        "[pairing]",
        "ttl_seconds = 600",
        "",
    ]
    return "\n".join(lines) + "\n"


def _check_provider_key(provider: str) -> bool:
    """Check if the provider's API key env var is set."""
    env_var = _PROVIDER_ENV_VARS.get(provider, "")
    if not env_var:
        return True
    return bool(os.environ.get(env_var, ""))


# ---------------------------------------------------------------------------
# Subcommand implementation
# ---------------------------------------------------------------------------


def _init(args: argparse.Namespace) -> None:
    """Initialize Arc — configure deployment tier and write config files."""
    tier: str | None = getattr(args, "tier", None)
    config_dir: str | None = getattr(args, "config_dir", None)
    provider: str | None = getattr(args, "provider", None)
    quick: bool = getattr(args, "quick", False)
    blueprint: str | None = getattr(args, "blueprint", None)

    _write("")
    _write("  Arc — Security-First Agent Framework")
    _write("  ====================================")
    _write("")

    if quick:
        tier = "personal"
    elif tier is None:
        _write("  How do you want to deploy?")
        _write("")
        _write("  1) quick start  — Minimal config, create an agent immediately")
        _write("  2) personal     — No security modules, basic defaults")
        _write("  3) enterprise   — Telemetry, audit, rate limiting, retry + fallback")
        _write("  4) federal      — Full security: routing, PII, signing, OTel, audit")
        _write("")
        choice = input("  Select [1/2/3/4] (default: 1): ").strip() or "1"
        tier_map = {"1": "personal", "2": "personal", "3": "enterprise", "4": "federal"}
        tier = tier_map.get(choice, "personal")
        quick = choice == "1"

    if provider is None:
        _write("")
        _write("  LLM Providers:")
        _write("    Cloud:  anthropic, openai, google, groq, mistral, deepseek")
        _write("    Local:  ollama, lmstudio (no API key needed)")
        _write("")
        provider = input("  Default provider (default: anthropic): ").strip() or "anthropic"
        if provider not in _VALID_PROVIDERS:
            sys.stderr.write(f"Error: Unknown provider '{provider}'.\n")
            sys.exit(1)

    arc_dir = Path(config_dir) if config_dir else Path.home() / ".arc"
    arc_dir.mkdir(parents=True, exist_ok=True)

    try:
        arcagent_content, effective_tier = _generate_arcagent_toml(tier, blueprint)
    except (FileNotFoundError, ValueError) as exc:
        sys.stderr.write(f"Error: {exc}\n")
        sys.exit(1)

    targets: list[tuple[Path, str]] = [
        (arc_dir / "arcllm.toml", _generate_arcllm_toml(tier, provider)),
        (arc_dir / "arcagent.toml", arcagent_content),
        (arc_dir / "gateway.toml", _generate_gateway_toml(tier)),
    ]

    existing = [p for p, _ in targets if p.exists()]
    if existing and not quick:
        names = ", ".join(p.name for p in existing)
        ans = input(f"  These files already exist: {names}. Overwrite? [y/N]: ").strip().lower()
        if ans not in ("y", "yes"):
            _write("  Aborted.")
            return

    for path, content in targets:
        path.write_text(content, encoding="utf-8")

    env_path = arc_dir / ".env"
    if not env_path.exists():
        env_path.touch(mode=0o600)

    # SPEC-053 — the deployment operator key (audit authority for every WORM
    # chain), distinct from any agent DID. Generated once, idempotent. All
    # crypto is delegated to arctrust. Enterprise/federal print the pubkey
    # fingerprint for out-of-band recording (anti-genesis-substitution +
    # witness bootstrap); personal is silent/zero-config.
    from arccli.commands.operator import ensure_operator_key

    operator = ensure_operator_key(arc_dir)
    if tier in ("enterprise", "federal"):
        _write(f"  Operator key fingerprint: {operator.public_key.hex()[:16]}")

    if tier in ("enterprise", "federal"):
        team_dir = arc_dir / "team"
        for sub in ("entities", "channels", "cursors"):
            (team_dir / sub).mkdir(parents=True, exist_ok=True)

    key_ok = _check_provider_key(provider)
    env_var = _PROVIDER_ENV_VARS.get(provider, "")

    tier_display = tier if effective_tier == tier else f"{effective_tier} (raised from {tier})"
    summary = [
        ("Tier", tier_display),
        ("Provider", provider),
        ("Config dir", str(arc_dir)),
        ("Files", ", ".join(p.name for p, _ in targets)),
        ("API key", "OK" if key_ok else f"MISSING ({env_var})"),
    ]
    if blueprint:
        summary.insert(1, ("Blueprint", blueprint))

    _write("")
    _write("  Configuration Summary:")
    _print_kv(summary)

    if not key_ok:
        _write("")
        _write("  Set your API key:")
        _write(f"    export {env_var}=<your-key>")
        _write("")
        _write(f"  Or add it to {env_path}:")
        _write(f"    echo '{env_var}=sk-...' >> {env_path}")

    _write("")


# ---------------------------------------------------------------------------
# Argparse-based dispatcher
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    """Build the argparse parser for `arc init`."""
    parser = argparse.ArgumentParser(
        prog="arc init",
        description="Initialize Arc — configure deployment tier and write config files.",
        add_help=True,
    )
    parser.add_argument(
        "--tier",
        choices=_VALID_TIERS,
        default=None,
        help="Deployment tier (personal/enterprise/federal).",
    )
    parser.add_argument(
        "--dir", dest="config_dir", default=None, help="Config directory (default: ~/.arc)."
    )
    parser.add_argument("--provider", default=None, help="Default LLM provider.")
    parser.add_argument("--quick", action="store_true", help="Quick start — personal tier.")
    parser.add_argument(
        "--blueprint",
        default=None,
        help="Bootstrap from a preset blueprint (deep-merged UNDER init defaults).",
    )
    return parser


def init_handler(args: list[str]) -> None:
    """Top-level handler for `arc init [args]`.

    Called by arccli.commands.registry when the user runs `arc init ...`.
    """
    parser = _build_parser()
    parsed = parser.parse_args(args)
    _init(parsed)
