"""arcrun — async execution engine for autonomous agents."""

__version__ = "0.11.0"

from arcrun._messages import SystemPrompt, content_text, system_messages
from arcrun.builtins import (
    ExecutionIsolationError,
    SandboxError,
    SandboxOOMError,
    SandboxRuntimeError,
    SandboxTimeoutError,
    SandboxUnavailableError,
    make_execute_tool,
    run_shell,
)
from arcrun.capabilities import (
    CapabilityProvider,
    CapabilityResult,
    CapabilitySpec,
    StaticProvider,
    detached_context,
    provider_tools,
)
from arcrun.checkpoint import LoopCheckpoint, apply_checkpoint, to_checkpoint
from arcrun.dynamic.seal import RunSeal, SealBroken, SealSigner
from arcrun.events import GENESIS_PREV_HASH, ChainVerificationResult, Event, EventBus, verify_chain
from arcrun.loop import (
    RunHandle,
    StructuredCallError,
    run,
    run_async,
    run_oneshot,
    run_structured,
)
from arcrun.model import (
    ContentBlock,
    Delta,
    EmbeddingProvider,
    EmbeddingUnavailable,
    ImageBlock,
    LLMProvider,
    LLMResponse,
    Message,
    Model,
    ModelAPIError,
    ModelErrorKind,
    ModelModuleKind,
    ModelModuleSetting,
    ModelTool,
    ProviderKey,
    ResponseFormat,
    StopReason,
    TextBlock,
    ToolCall,
    ToolCallDelta,
    ToolResultBlock,
    ToolUseBlock,
    TraceStore,
    Usage,
    create_model_trace_store,
    embed_texts,
    iter_model_modules,
    load_model,
    model_api_error,
    model_config_path,
    model_identity,
    model_provider_keys,
    validate_model_modules,
)
from arcrun.parallel_dispatch import dispatch_ready
from arcrun.prompts import get_strategy_prompts
from arcrun.registry import ToolRegistry
from arcrun.strategies import Strategy, available_strategies
from arcrun.streams import (
    RunResult,
    StreamEvent,
    TokenEvent,
    ToolEndEvent,
    ToolStartEvent,
    TurnEndEvent,
    collect,
    run_stream,
    stream_llm_response,
)
from arcrun.types import LoopResult, ParentRunContext, SandboxConfig, Tool, ToolContext

__all__ = [
    "GENESIS_PREV_HASH",
    "CapabilityProvider",
    "CapabilityResult",
    "CapabilitySpec",
    "ChainVerificationResult",
    "ContentBlock",
    "Delta",
    "EmbeddingProvider",
    "EmbeddingUnavailable",
    "Event",
    "EventBus",
    "ExecutionIsolationError",
    "ImageBlock",
    "LLMProvider",
    "LLMResponse",
    "LoopCheckpoint",
    "LoopResult",
    "Message",
    "Model",
    "ModelAPIError",
    "ModelErrorKind",
    "ModelModuleKind",
    "ModelModuleSetting",
    "ModelTool",
    "ParentRunContext",
    "ProviderKey",
    "ResponseFormat",
    "RunHandle",
    "RunResult",
    "RunSeal",
    "SandboxConfig",
    "SandboxError",
    "SandboxOOMError",
    "SandboxRuntimeError",
    "SandboxTimeoutError",
    "SandboxUnavailableError",
    "SealBroken",
    "SealSigner",
    "StaticProvider",
    "StopReason",
    "Strategy",
    "StreamEvent",
    "StructuredCallError",
    "SystemPrompt",
    "TextBlock",
    "TokenEvent",
    "Tool",
    "ToolCall",
    "ToolCallDelta",
    "ToolContext",
    "ToolEndEvent",
    "ToolRegistry",
    "ToolResultBlock",
    "ToolStartEvent",
    "ToolUseBlock",
    "TraceStore",
    "TurnEndEvent",
    "Usage",
    "__version__",
    "apply_checkpoint",
    "available_strategies",
    "collect",
    "content_text",
    "create_model_trace_store",
    "detached_context",
    "dispatch_ready",
    "embed_texts",
    "get_strategy_prompts",
    "iter_model_modules",
    "load_model",
    "make_execute_tool",
    "model_api_error",
    "model_config_path",
    "model_identity",
    "model_provider_keys",
    "provider_tools",
    "run",
    "run_async",
    "run_oneshot",
    "run_shell",
    "run_stream",
    "run_structured",
    "stream_llm_response",
    "system_messages",
    "to_checkpoint",
    "validate_model_modules",
    "verify_chain",
]
