"""A reusable spec-conformant MCP server fixture, built on the real ``mcp`` SDK.

SPEC-084 (REQ-455, CON-15) needs a server the client can be *proven* against —
not a hand-rolled JSON-RPC stub that would only re-encode our own assumptions.
This fixture is therefore a genuine ``mcp``-SDK server (``FastMCP``), the same
kind of server Composio, Microsoft, or any hosted vendor runs. It speaks whatever
protocol revision the installed SDK implements and negotiates the handshake for
real, so a test driving it exercises the actual wire.

**On revisions.** The installed SDK (``mcp==1.29.0``) implements the Legacy
``initialize`` handshake (it negotiates protocol revision ``2025-11-25``); it does
*not* implement the ``2026-07-28`` ``server/discover`` stateless revision the old
hand-rolled client targeted. Because the whole ecosystem is Legacy, a single real
SDK server *is* the meaningful conformance target — no second "modern stateless"
server exists to build against at this SDK version. If a future SDK adds another
revision, add it here; the client must keep negotiating whatever the server offers.

The fixture uses the SDK's in-memory connected client/server helper, so no socket
or subprocess is needed: :func:`connected_session_factory` returns a zero-argument
factory that, each time it is entered, spins up a fresh in-memory transport, runs
the ``FastMCP`` server on one end, and yields a connected, already-initialized
:class:`mcp.ClientSession` on the other. That factory is exactly the injectable
seam the SDK-backed client consumes: in production the factory wraps
``streamablehttp_client`` / ``stdio_client``; in a test it wraps this fixture.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable
from contextlib import AbstractAsyncContextManager

from mcp import ClientSession
from mcp.server.fastmcp import FastMCP
from mcp.shared.memory import create_connected_server_and_client_session

#: The one tool every conformance test relies on. A bare ``echo`` is enough to
#: prove list + call over the real protocol without any server-side state.
ECHO_TOOL_NAME = "echo"


def build_fake_mcp_server(name: str = "fake-arc-mcp") -> FastMCP:
    """Build a minimal spec-conformant MCP server exposing an ``echo`` tool.

    The tool's single ``text`` parameter and its return type are read by the SDK
    off the function signature, so the served ``inputSchema`` is generated by the
    SDK exactly as a real server's would be — the fixture never hand-writes it.
    """
    server = FastMCP(name=name)

    @server.tool(description="Echo the given text straight back to the caller.")
    def echo(text: str) -> str:
        return f"echo: {text}"

    return server


def build_named_mcp_server(tool_names: Iterable[str], name: str = "fake-arc-mcp") -> FastMCP:
    """Build a real SDK server that serves each named tool, echoing ``ran <name>``.

    A hosted broker (Composio) advertises tools whose names come from its own
    catalogue, and a conformance test needs to serve an *arbitrary* set — including
    a rogue verb outside the manifest allowlist — over the real protocol. Each tool
    takes no arguments, so the SDK generates an empty object schema for it exactly
    as it would for a real no-argument verb, and returns a marker the caller can
    assert the call reached the server.
    """
    server = FastMCP(name=name)

    def _make(bound: str) -> Callable[[], str]:
        def served() -> str:
            return f"ran {bound}"

        return served

    for tool_name in tool_names:
        server.add_tool(_make(tool_name), name=tool_name, description=tool_name)
    return server


def connected_session_factory(
    server: FastMCP | None = None,
) -> Callable[[], AbstractAsyncContextManager[ClientSession]]:
    """Return a factory yielding a connected, initialized client session.

    Each call to the returned factory produces a *fresh* in-memory connection to
    the given (or a default ``echo``) server: a new client/server memory-stream
    pair, the ``FastMCP`` server running on the server end, and a fully
    initialized :class:`mcp.ClientSession` on the client end. The factory is
    therefore re-enterable — a client that opens one session per operation gets a
    clean handshake every time, which is what makes it a drop-in for the
    production HTTP/stdio session factories.
    """
    target = server if server is not None else build_fake_mcp_server()

    def factory() -> AbstractAsyncContextManager[ClientSession]:
        return create_connected_server_and_client_session(target)

    return factory
