"""Turn an operator's description of an MCP server into a signed connector bundle.

Arc is already an MCP client: a connector bundle with ``attachment = "mcp"`` is
what selects the SDK client. Until now the only way to add a server was to
hand-write that bundle. This module is the one place that does it for the
operator — and because an MCP server is third-party code reached over a wire or a
child process, the generated bundle IS the trust boundary. Every refusal that
protects it lives here, where the spec is built, before anything is written:

* **What may launch.** A stdio server must resolve to one executable on this host
  (an absolute path; a bare name is resolved once and pinned). No shell
  metacharacters, no relative paths, no shells or wrappers, no inline-code flags.
  Above personal tier the executable must also be on the operator's allowlist.
* **Where it may connect.** https only (plain http to loopback is a personal-tier
  convenience), no userinfo, no credential-looking query keys, and an SSRF guard:
  link-local, metadata, multicast and unspecified addresses are refused whether
  typed as a literal, as a numeric trick, or reached by name.
* **What it may expose.** The operator chooses tools after seeing what the server
  advertises. Each is registered as ``<name>__<verb>``, so a server can never
  take the name of a built-in tool, and its classification and capability tags
  come from the operator's choice, never from the server describing itself.
* **Who vouched.** Every generated byte is signed by the operator key and is
  re-verified at load, so editing the bundle afterwards makes it refuse to load.

Secrets are never part of the spec or the bundle. The spec names which fields the
server needs; the values go through the existing secret path at install time.
"""

from __future__ import annotations

import asyncio
import hashlib
import ipaddress
import json
import os
import re
import shutil
import socket
import stat
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal
from urllib.parse import urlsplit

from arctrust.signer import Signer
from pydantic import BaseModel, ConfigDict, Field, model_validator

from arcagent.capabilities import artifact_signing
from arcagent.core.errors import ExtensionError
from arcagent.core.session_internal.capability_ledger import TAG_TO_LEGS
from arcagent.core.tier import Tier
from arcagent.extension.attachment import Classification, ExtensionAttachment
from arcagent.extension.catalog import BUNDLES_DIRNAME, MANIFEST_NAME
from arcagent.extension.environment import refuses_placement
from arcagent.extension.manifest import load_manifest
from arcagent.extension.secrets import Secret
from arcagent.modules.connectors.attachments import build_attachment

#: The one error code every refusal in this module carries, so a surface branches
#: on a code rather than on prose.
MCP_SPEC_REFUSED = "MCP_SPEC_REFUSED"
MCP_DISCOVERY_FAILED = "MCP_DISCOVERY_FAILED"

#: The name of the single credential an http server's auth header carries.
HTTP_CREDENTIAL_FIELD = "credential"

#: Tool names a transport suggests tags for. An http server receives the agent's
#: arguments (egress) and returns content nobody on this host vetted (untrusted
#: input); a local child process is only the second.
DEFAULT_HTTP_TAGS: tuple[str, ...] = ("network_egress", "web")
DEFAULT_STDIO_TAGS: tuple[str, ...] = ("subprocess",)

#: The first line of every generated manifest. It is how Arc tells a bundle it wrote from
#: one an operator wrote by hand, so only the former is ever replaced automatically.
GENERATED_MARKER = "# Generated by `arc connector add-mcp`"

KNOWLEDGE_REASON = (
    "An MCP server exposes callable tools only. It publishes no enumerable document "
    "corpus and no change feed, so there is nothing to map, sync incrementally or "
    "revoke into Knowledge. An agent reaches it through the tools it is granted."
)

_NAME_PATTERN = r"^[a-z][a-z0-9_]{0,31}$"
_VERB = re.compile(r"[A-Za-z0-9_-]{1,48}")
_SECRET_NAME = re.compile(r"[a-z][a-z0-9_]{0,31}")
_ENV_VARIABLE = re.compile(r"[A-Z_][A-Z0-9_]{0,63}")
_HEADER_NAME = re.compile(r"[A-Za-z][A-Za-z0-9-]{0,63}")
_HEADER_SCHEME = re.compile(r"[A-Za-z0-9._-]{0,32}")
_SHELL_METACHARACTERS = re.compile(r"[;&|`$<>\\\x00-\x1f\x7f]")
_NUMERIC_HOST = re.compile(r"(0x[0-9a-f]+|\d+)(\.(0x[0-9a-f]+|\d+))*")
_CREDENTIAL_QUERY_KEY = re.compile(
    r"(key|token|secret|passw|auth|credential|signature|sig)", re.IGNORECASE
)
_TOOL_NAME_LIMIT = 64
_MAX_ARGV = 64
_MAX_TOKEN = 1024
_DESCRIPTION_LIMIT = 200

#: Programs that run arbitrary text or arbitrary other programs. A server is a
#: program that speaks MCP; these only ever make "arbitrary binaries" reachable.
_INTERPRETER_WRAPPERS = frozenset(
    {
        "sh", "bash", "zsh", "dash", "ksh", "fish", "csh", "tcsh", "ash",
        "cmd", "cmd.exe", "powershell", "powershell.exe", "pwsh", "env", "xargs",
        "sudo", "doas", "su", "nohup", "eval", "exec", "busybox",
    }
)  # fmt: skip
_INLINE_CODE_FLAGS = frozenset({"-c", "-e", "--eval", "--exec", "--command"})

#: Headers an operator must not point a credential at: the ones that frame the
#: request itself, where a credential value would corrupt or smuggle it.
_FORBIDDEN_HEADERS = frozenset(
    {
        "host", "content-length", "content-type", "transfer-encoding", "connection",
        "upgrade", "te", "trailer", "expect", "cookie", "set-cookie",
    }
)  # fmt: skip

_METADATA_HOSTNAMES = frozenset(
    {
        "metadata", "metadata.goog", "metadata.google.internal", "instance-data",
        "instance-data.ec2.internal", "metadata.azure.com",
    }
)  # fmt: skip
_METADATA_ADDRESSES = frozenset(
    ipaddress.ip_address(text)
    for text in ("169.254.169.254", "fd00:ec2::254", "100.100.100.200", "192.0.0.192")
)

Resolver = Callable[[str], Sequence[str]]
Which = Callable[[str], str | None]


def _refuse(message: str, **details: Any) -> ExtensionError:
    return ExtensionError(code=MCP_SPEC_REFUSED, message=message, details=details or None)


class McpToolChoice(BaseModel):
    """One tool the operator chose to expose, and how it is to be treated.

    ``classification`` and ``capability_tags`` are the operator's declaration. The
    server's own annotations are never consulted (a lying server would otherwise
    describe itself as read-only and ungated).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    classification: Classification = "state_modifying"
    capability_tags: tuple[str, ...] = ()
    description: str = ""


class McpServerSpec(BaseModel):
    """Everything the operator says about one MCP server. Never a secret value."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str = Field(pattern=_NAME_PATTERN)
    display: str = ""
    description: str = ""
    transport: Literal["http", "stdio"]
    url: str = ""
    auth_header: str = ""
    auth_scheme: str = "Bearer"
    argv: tuple[str, ...] = ()
    env_refs: dict[str, str] = Field(default_factory=dict)
    tools: dict[str, McpToolChoice] = Field(default_factory=dict)
    approval_default: Literal["none", "outbound", "all"] = "outbound"

    @model_validator(mode="after")
    def _transport_fields_do_not_mix(self) -> McpServerSpec:
        if self.transport == "http":
            if not self.url:
                raise ValueError("an http server needs a url")
            if self.argv or self.env_refs:
                raise ValueError("an http server takes no command or environment")
        else:
            if not self.argv:
                raise ValueError("a stdio server needs a command")
            if self.url or self.auth_header:
                raise ValueError("a stdio server takes no url or auth header")
        return self

    @property
    def secret_fields(self) -> tuple[str, ...]:
        """The credential fields the operator must supply, by name."""
        if self.transport == "http":
            return (HTTP_CREDENTIAL_FIELD,) if self.auth_header else ()
        return tuple(self.env_refs)

    def namespaced(self, verb: str) -> str:
        """The name an agent sees for one of this server's tools."""
        return f"{self.name}__{verb}"


@dataclass(frozen=True)
class DiscoveredTool:
    """One tool a server advertised, as shown to the operator choosing which to expose.

    ``description`` is the server's own text: untrusted, collapsed to one line and
    capped. It is displayed, never executed and never copied into the manifest.
    """

    name: str
    description: str
    usable: bool
    reason: str = ""


# --- validation --------------------------------------------------------------


def validate_spec(
    spec: McpServerSpec,
    *,
    tier: Tier,
    stdio_allow: Sequence[str] = (),
    resolver: Resolver | None = None,
    which: Which | None = None,
) -> McpServerSpec:
    """Refuse an unsafe spec; return it with its command resolved to an absolute path.

    Raises:
        ExtensionError: ``MCP_SPEC_REFUSED``, with a message written for the operator.
    """
    if tier is Tier.FEDERAL:
        raise _refuse(
            "federal deployments connect only vetted, signed bundles from the official "
            "allowlist; an operator-added MCP server is refused at federal tier",
            reason="federal",
        )
    resolved = spec
    if spec.transport == "http":
        _check_url(spec.url, tier, resolver or _system_resolver)
        _check_header(spec.auth_header, spec.auth_scheme)
    else:
        resolved = spec.model_copy(
            update={"argv": _check_command(spec.argv, tier, stdio_allow, which or shutil.which)}
        )
        _check_environment(spec.env_refs)
    _check_tools(spec)
    return resolved


def _check_url(url: str, tier: Tier, resolver: Resolver) -> None:
    try:
        parts = urlsplit(url)
        host = (parts.hostname or "").lower()
        _ = parts.port
    except ValueError as exc:
        raise _refuse(f"the url is not valid: {exc}", reason="url") from exc
    if parts.scheme not in {"http", "https"} or not host:
        raise _refuse("the url must be an https address", reason="scheme")
    if parts.username is not None or parts.password is not None or "@" in parts.netloc:
        raise _refuse(
            "the url must not carry userinfo; put credentials in the header", reason="userinfo"
        )
    if parts.fragment:
        raise _refuse("the url must not carry a fragment", reason="fragment")
    if any(
        _CREDENTIAL_QUERY_KEY.search(pair.split("=", 1)[0])
        for pair in parts.query.split("&")
        if pair
    ):
        raise _refuse(
            "the url query looks like it carries a credential; put it in the auth header",
            reason="query",
        )
    if parts.scheme == "http" and not _names_loopback(host):
        # Decided before any DNS lookup: a plain-http remote is refused on its scheme
        # alone, so a refused URL never makes the network call that would test it.
        raise _refuse(
            "the url must be https (plain http is allowed only to loopback at personal tier)",
            reason="scheme",
        )
    addresses = _addresses_of(host, resolver)
    loopback = all(address.is_loopback for address in addresses)
    for address in addresses:
        _refuse_if_blocked(host, address)
    if loopback and tier is not Tier.PERSONAL:
        raise _refuse(
            "loopback addresses (and plain http) are reachable at personal tier only; "
            "use an https address",
            reason="loopback",
        )
    if parts.scheme != "https" and not (loopback and tier is Tier.PERSONAL):
        raise _refuse(
            "the url must be https (plain http is allowed only to loopback at personal tier)",
            reason="scheme",
        )


def _names_loopback(host: str) -> bool:
    if host == "localhost":
        return True
    try:
        return ipaddress.ip_address(host).is_loopback
    except ValueError:
        return False


def _addresses_of(
    host: str, resolver: Resolver
) -> list[ipaddress.IPv4Address | ipaddress.IPv6Address]:
    if host in _METADATA_HOSTNAMES:
        raise _refuse(f"{host} is a cloud metadata service name", reason="ssrf")
    try:
        return [_unmapped(ipaddress.ip_address(host))]
    except ValueError:
        pass
    if _NUMERIC_HOST.fullmatch(host):
        raise _refuse(f"{host} is an ambiguous numeric address", reason="ssrf")
    try:
        found = [str(item) for item in resolver(host)]
    except OSError as exc:
        raise _refuse(f"could not resolve {host}: {exc}", reason="resolve") from exc
    if not found:
        raise _refuse(f"could not resolve {host}", reason="resolve")
    try:
        return [_unmapped(ipaddress.ip_address(item.split("%", 1)[0])) for item in found]
    except ValueError as exc:
        raise _refuse(
            f"{host} resolved to something that is not an address", reason="resolve"
        ) from exc


def _unmapped(
    address: ipaddress.IPv4Address | ipaddress.IPv6Address,
) -> ipaddress.IPv4Address | ipaddress.IPv6Address:
    """Unwrap ``::ffff:a.b.c.d`` so a mapped metadata address is judged as IPv4."""
    if isinstance(address, ipaddress.IPv6Address) and address.ipv4_mapped is not None:
        return address.ipv4_mapped
    return address


def _refuse_if_blocked(host: str, address: ipaddress.IPv4Address | ipaddress.IPv6Address) -> None:
    if (
        address in _METADATA_ADDRESSES
        or address.is_link_local
        or address.is_multicast
        or address.is_unspecified
        or address.is_reserved
    ):
        raise _refuse(
            f"{host} points at {address}, a link-local, metadata or otherwise unreachable "
            "address that an MCP server may not use",
            reason="ssrf",
        )


def _system_resolver(host: str) -> list[str]:
    return [str(info[4][0]) for info in socket.getaddrinfo(host, None, proto=socket.IPPROTO_TCP)]


def _check_header(header: str, scheme: str) -> None:
    if not header:
        return
    if not _HEADER_NAME.fullmatch(header) or header.lower() in _FORBIDDEN_HEADERS:
        raise _refuse(f"{header!r} cannot carry a credential header", reason="header")
    if not _HEADER_SCHEME.fullmatch(scheme):
        raise _refuse("the auth scheme must be a plain word such as Bearer", reason="header")


def _check_command(
    argv: Sequence[str], tier: Tier, stdio_allow: Sequence[str], which: Which
) -> tuple[str, ...]:
    if len(argv) > _MAX_ARGV or any(len(token) > _MAX_TOKEN for token in argv):
        raise _refuse("the command is too long", reason="argv")
    for token in argv:
        if _SHELL_METACHARACTERS.search(token):
            raise _refuse(
                f"{token!r} contains a shell metacharacter; the command is run directly, "
                "never through a shell",
                reason="metacharacter",
            )
    command, *arguments = argv
    if any(ch.isspace() or ch in "'\"" for ch in command):
        raise _refuse("the command must be one program name or path", reason="metacharacter")
    name = os.path.basename(command).lower()
    if name in _INTERPRETER_WRAPPERS:
        raise _refuse(
            f"{name} is a shell or interpreter wrapper, not an MCP server", reason="interpreter"
        )
    if any(token in _INLINE_CODE_FLAGS for token in arguments):
        raise _refuse(
            "inline code flags (-c, -e) are not allowed in a server command", reason="inline"
        )
    resolved = _resolve_executable(command, which)
    _check_allowlist(resolved, tier, stdio_allow)
    return (resolved, *arguments)


def _resolve_executable(command: str, which: Which) -> str:
    if "/" in command or command.startswith("~"):
        if not os.path.isabs(command):
            raise _refuse(
                f"{command!r} is a relative path; use an absolute path or a bare program name",
                reason="relative",
            )
        path = Path(command)
        if not path.is_file():
            raise _refuse(f"{command} was not found on this host", reason="missing")
        if not os.access(path, os.X_OK) or not path.stat().st_mode & stat.S_IXUSR:
            raise _refuse(f"{command} is not executable", reason="not_executable")
        return command
    found = which(command)
    if not found or not os.path.isabs(found):
        raise _refuse(f"{command} was not found on this host's PATH", reason="missing")
    return found


def _check_allowlist(resolved: str, tier: Tier, stdio_allow: Sequence[str]) -> None:
    if tier is Tier.PERSONAL:
        return
    allowed = {entry for entry in stdio_allow if entry}
    if resolved in allowed or os.path.basename(resolved) in allowed:
        return
    raise _refuse(
        f"{resolved} is not on this deployment's stdio allowlist "
        "([tools.policy] mcp_stdio_allow); above personal tier only listed programs may launch",
        reason="allowlist",
    )


def _check_environment(env_refs: Mapping[str, str]) -> None:
    for secret, variable in env_refs.items():
        if not _SECRET_NAME.fullmatch(secret):
            raise _refuse(f"{secret!r} is not a valid credential field name", reason="env")
        if not _ENV_VARIABLE.fullmatch(variable) or refuses_placement(variable):
            raise _refuse(
                f"{variable!r} cannot receive a credential: it is not a plain variable name, "
                "or it steers how the child process starts",
                reason="env",
            )


def _check_tools(spec: McpServerSpec) -> None:
    for verb, choice in spec.tools.items():
        if not _VERB.fullmatch(verb) or len(spec.namespaced(verb)) > _TOOL_NAME_LIMIT:
            raise _refuse(
                f"{verb!r} is not a usable tool name (letters, digits, '_' and '-', and "
                f"{_TOOL_NAME_LIMIT} characters with the '{spec.name}__' prefix)",
                reason="tool_name",
            )
        unknown = [tag for tag in choice.capability_tags if tag not in TAG_TO_LEGS]
        if unknown:
            raise _refuse(
                f"unknown capability tag(s) {', '.join(unknown)} on {verb!r}", reason="tag"
            )


# --- rendering ----------------------------------------------------------------


def render_extension_toml(spec: McpServerSpec, *, require_tools: bool = True) -> str:
    """The bundle's ``extension.toml``, in the shape the shipped Composio bundle has.

    Rendered from a validated spec only. Every operator-supplied string goes
    through :func:`_q`, so none can break out of its TOML value.
    """
    if require_tools and not spec.tools:
        raise _refuse("choose at least one tool to expose", reason="no_tools")
    lines = [
        GENERATED_MARKER + " / the Add MCP server dialog. Edit nothing here:",
        "# every file in this folder is signed; a changed byte makes the bundle refuse to load.",
        "[extension]",
        f"name = {_q(spec.name)}",
        f"display_name = {_q(spec.display or spec.name)}",
        'version = "1.0.0"',
        f"description = {_q(spec.description or f'Tools from the {spec.name} MCP server.')}",
        'attachment = "mcp"',
        'tier_floor = "personal"',
        "",
        "[knowledge]",
        'mode = "non_indexable"',
        f"reason = {_q(KNOWLEDGE_REASON)}",
        "",
        *_secret_tables(spec),
        "[health]",
        'probe = "attachment"',
        "",
        "[tools]",
        f"allow = [{', '.join(_q(spec.namespaced(verb)) for verb in spec.tools)}]",
        "",
        *_declared_tables(spec),
        "[approval]",
        f"default = {_q(spec.approval_default)}",
        "",
        "[config.mcp]",
        *_transport_lines(spec),
        'client_name = "arc"',
        f"namespace = {_q(spec.name)}",
        "",
        "[config.mcp.resilience]",
        "timeout_seconds = 60.0",
        "max_attempts = 3",
        "",
        *_policy_tables(spec),
    ]
    return "\n".join(lines).rstrip() + "\n"


def _q(value: str) -> str:
    """A TOML basic string. JSON string escaping is a strict subset of it."""
    return json.dumps(value)


def _secret_tables(spec: McpServerSpec) -> list[str]:
    if spec.transport == "http" and spec.auth_header:
        return [
            "[[secrets]]",
            f"name = {_q(HTTP_CREDENTIAL_FIELD)}",
            "prompt = "
            + _q(f"Credential for {spec.name}, sent in its {spec.auth_header} header."),
            "sensitive = true",
            "",
        ]
    lines: list[str] = []
    for secret, variable in spec.env_refs.items():
        lines += [
            "[[secrets]]",
            f"name = {_q(secret)}",
            f"prompt = {_q(f'Value {spec.name} reads from the {variable} variable.')}",
            "sensitive = true",
            "",
            "[secrets.placement]",
            f"variable = {_q(variable)}",
            "",
        ]
    return lines


def _declared_tables(spec: McpServerSpec) -> list[str]:
    lines: list[str] = []
    for verb, choice in spec.tools.items():
        lines += [
            "[[tools.declared]]",
            f"name = {_q(spec.namespaced(verb))}",
            f"description = {_q(_one_line(choice.description))}",
            f"classification = {_q(choice.classification)}",
            f"capability_tags = [{', '.join(_q(tag) for tag in choice.capability_tags)}]",
            "",
        ]
    return lines


def _transport_lines(spec: McpServerSpec) -> list[str]:
    if spec.transport == "stdio":
        return [
            'transport = "stdio"',
            f"argv = [{', '.join(_q(token) for token in spec.argv)}]",
            "install_instruction = "
            + _q(f"Install {os.path.basename(spec.argv[0])} on this host."),
        ]
    parts = urlsplit(spec.url)
    default_port = {"http": 80, "https": 443}[parts.scheme]
    port = "" if parts.port in (None, default_port) else f":{parts.port}"
    host = parts.hostname or ""
    origin = f"{parts.scheme}://{f'[{host}]' if ':' in host else host}{port}/"
    lines = [
        'transport = "http"',
        f"url = {_q(spec.url)}",
        f"url_origin = {_q(origin)}",
    ]
    if spec.auth_header:
        lines += [
            f"credential_field = {_q(HTTP_CREDENTIAL_FIELD)}",
            f"auth_header = {_q(spec.auth_header)}",
            f"auth_scheme = {_q(spec.auth_scheme)}",
        ]
    return lines


def _policy_tables(spec: McpServerSpec) -> list[str]:
    lines: list[str] = []
    for verb, choice in spec.tools.items():
        lines += [
            f"[config.mcp.tools.{_q(verb)}]",
            f"classification = {_q(choice.classification)}",
            f"capability_tags = [{', '.join(_q(tag) for tag in choice.capability_tags)}]",
            "",
        ]
    return lines


def _one_line(text: str) -> str:
    cleaned = re.sub(r"[\x00-\x1f\x7f]+", " ", text)
    return " ".join(cleaned.split())[:_DESCRIPTION_LIMIT]


# --- writing and signing ------------------------------------------------------


def write_bundle(
    spec: McpServerSpec,
    arc_dir: Path,
    *,
    replace: bool = False,
    other_roots: Sequence[Path] = (),
    bundles_dirname: str = BUNDLES_DIRNAME,
) -> Path:
    """Write the bundle to ``<arc_dir>/extensions/<name>/`` and return its folder.

    Built in a private sibling folder and moved into place, so a crash never leaves
    a half-written bundle where the catalog would find it. Refuses to overwrite
    without ``replace``, refuses a name any other root already holds (a generated
    bundle must never shadow a shipped one), and refuses a symlinked destination.

    Raises:
        ExtensionError: The destination is unsafe or already taken.
    """
    root = Path(arc_dir) / bundles_dirname
    target = root / spec.name
    text = render_extension_toml(spec)
    if target.is_symlink():
        raise _refuse(f"{target} is a symlink; refusing to write through it", reason="symlink")
    if target.exists() and not replace:
        raise _refuse(f"a bundle named {spec.name!r} already exists at {target}", reason="exists")
    for other in other_roots:
        held = Path(other) / spec.name
        if Path(other).resolve() != root.resolve() and (held.exists() or held.is_symlink()):
            raise _refuse(f"the name {spec.name!r} is already used by {held}", reason="collision")
    root.mkdir(parents=True, exist_ok=True)
    staging = root / f".{spec.name}.staging-{os.getpid()}"
    shutil.rmtree(staging, ignore_errors=True)
    staging.mkdir(mode=0o755)
    try:
        manifest = staging / MANIFEST_NAME
        manifest.write_text(text, encoding="utf-8")
        manifest.chmod(0o644)
        if target.exists():
            shutil.rmtree(target)
        staging.replace(target)
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return target


def is_generated_bundle(folder: Path) -> bool:
    """Whether ``folder`` is a bundle this module wrote (and so may rewrite)."""
    manifest = Path(folder) / MANIFEST_NAME
    if Path(folder).is_symlink() or manifest.is_symlink() or not manifest.is_file():
        return False
    with manifest.open(encoding="utf-8") as handle:
        return handle.readline().startswith(GENERATED_MARKER)


def sign_bundle(folder: Path, *, signer: Signer, signer_did: str) -> list[Path]:
    """Sign every file in ``folder`` with the operator's signer; return the sidecars."""
    sidecars: list[Path] = []
    for path in sorted(folder.rglob("*")):
        if path.is_file() and path.suffix != artifact_signing.SIDECAR_SUFFIX:
            sidecars.append(
                artifact_signing.write_signature_with_signer(
                    path, path.read_bytes(), signer_did=signer_did, signer=signer
                )
            )
    return sidecars


def spec_digest(spec: McpServerSpec) -> str:
    """SHA-256 of the canonical spec. Safe to audit: a spec holds no secret value."""
    canonical = json.dumps(spec.model_dump(mode="json"), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# --- discovery ----------------------------------------------------------------

AttachmentBuilder = Callable[..., ExtensionAttachment]


async def discover_tools(
    spec: McpServerSpec,
    *,
    tier: Tier,
    secret_values: Mapping[str, str],
    stdio_allow: Sequence[str] = (),
    resolver: Resolver | None = None,
    which: Which | None = None,
    timeout: float = 30.0,
    builder: AttachmentBuilder | None = None,
) -> tuple[DiscoveredTool, ...]:
    """Ask the server what it offers, writing nothing and keeping nothing.

    Goes through the SAME attachment builder a connected account uses (origin
    guard, credential placement, environment scrub, sandbox wrap), so a preview
    cannot reach anywhere an install could not. ``secret_values`` live only in this
    call's memory.

    Raises:
        ExtensionError: The spec is refused, or the server did not answer in time.
    """
    checked = validate_spec(
        spec, tier=tier, stdio_allow=stdio_allow, resolver=resolver, which=which
    )
    _require_exactly(checked, secret_values)
    bare = checked.model_copy(update={"tools": {}})
    manifest = load_manifest(render_extension_toml(bare, require_tools=False), tier=tier)
    secrets = {name: Secret(value) for name, value in secret_values.items()}
    build = builder or build_attachment
    try:
        attachment = build(manifest, Path(os.devnull), secrets)
        specs = await asyncio.wait_for(attachment.describe_tools(), timeout=timeout)
    except TimeoutError as exc:
        raise ExtensionError(
            code=MCP_DISCOVERY_FAILED,
            message=f"the server did not list its tools within {timeout:g} seconds",
        ) from exc
    except ExtensionError:
        raise
    except Exception as exc:  # reason: any transport/SDK failure is one operator-facing refusal
        raise ExtensionError(
            code=MCP_DISCOVERY_FAILED,
            message=_redacted(
                f"could not list the server's tools: {type(exc).__name__}: {exc}", secret_values
            ),
        ) from exc
    return tuple(_discovered(checked, tool.name, tool.description) for tool in specs)


def _discovered(spec: McpServerSpec, advertised: str, description: str) -> DiscoveredTool:
    verb = advertised.removeprefix(f"{spec.name}__")
    clean = _one_line(description)
    if not _VERB.fullmatch(verb) or len(spec.namespaced(verb)) > _TOOL_NAME_LIMIT:
        return DiscoveredTool(verb[:80], clean, usable=False, reason="name cannot be exposed")
    return DiscoveredTool(verb, clean, usable=True)


def require_exactly(spec: McpServerSpec, secret_values: Mapping[str, str]) -> None:
    """Refuse missing or unexpected credential fields, naming fields never values."""
    _require_exactly(spec, secret_values)


def _require_exactly(spec: McpServerSpec, secret_values: Mapping[str, str]) -> None:
    wanted = set(spec.secret_fields)
    given = set(secret_values)
    missing = sorted(name for name in wanted if not secret_values.get(name))
    if missing:
        raise _refuse(f"missing credential value(s): {', '.join(missing)}", reason="secrets")
    if given - wanted:
        raise _refuse(
            f"unexpected credential field(s): {', '.join(sorted(given - wanted))}",
            reason="secrets",
        )


def _redacted(message: str, secret_values: Mapping[str, str]) -> str:
    for value in secret_values.values():
        if value:
            message = message.replace(value, "***")
    return message


__all__ = [
    "DEFAULT_HTTP_TAGS",
    "DEFAULT_STDIO_TAGS",
    "GENERATED_MARKER",
    "HTTP_CREDENTIAL_FIELD",
    "KNOWLEDGE_REASON",
    "MCP_DISCOVERY_FAILED",
    "MCP_SPEC_REFUSED",
    "DiscoveredTool",
    "McpServerSpec",
    "McpToolChoice",
    "discover_tools",
    "is_generated_bundle",
    "render_extension_toml",
    "require_exactly",
    "sign_bundle",
    "spec_digest",
    "validate_spec",
    "write_bundle",
]
